Repository hashicorp/vault-secrets-operator, pull requests merged in 2023-04, with the labels that each got.

#109 Fix "make test"
  hack/install_copywrite.sh
Labels: bug

#114 fix: docker cache improvement
  Dockerfile
Labels: enhancement, CI

#116 Run integrationTest as part of the build workflow
  .github/workflows/build.yaml
  .github/workflows/tests.yaml
  Makefile
  scripts/tffmtcheck.sh
  test/integration/integration_test.go
  test/integration/vaultpkisecret/terraform/main.tf
  test/integration/vaultpkisecret/terraform/variables.tf
  test/integration/vaultpkisecret_integration_test.go
  test/integration/vaultstaticsecret/terraform/main.tf
  test/integration/vaultstaticsecret/terraform/variables.tf
  test/integration/vaultstaticsecret_integration_test.go
Labels: enhancement, CI

#127 Check version of the binary in the image
  .github/workflows/build.yaml
  go.mod
  main.go
Labels: enhancement, CI

#143 Adds support for revocation of VDS secrets on delete.
  CHANGELOG.md
  api/v1alpha1/vaultdynamicsecret_types.go
  chart/crds/vaultdynamicsecret-crd.yaml
  config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
  controllers/vaultdynamicsecret_controller.go
  internal/consts/reasons.go
  test/integration/integration_test.go
  test/integration/vaultdynamicsecret/terraform/postgres.tf
  test/integration/vaultdynamicsecret_integration_test.go
Labels: enhancement

#154 Adding testing framework for EKS
  Makefile
  README.md
  test/integration/infra/eks/main.tf
  test/integration/infra/eks/outputs.tf
  test/integration/infra/eks/providers.tf
  test/integration/infra/eks/variables.tf
  test/integration/vaultdynamicsecret_integration_test.go
  test/integration/vaultpkisecret_integration_test.go
  test/integration/vaultstaticsecret_integration_test.go
Labels: CI

#156 Add integration-test-helm-ent and make it the default for matrix
  .github/workflows/build.yaml
  Makefile
Labels: CI

#131 feat: add support for the JWT auth method
  CHANGELOG.md
  api/v1alpha1/vaultauth_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/crds/vaultauth-crd.yaml
  chart/templates/default-vault-auth-method.yaml
  chart/values.yaml
  config/crd/bases/secrets.hashicorp.com_vaultauths.yaml
  config/manager/kustomization.yaml
  internal/vault/cache_key.go
  internal/vault/cache_key_test.go
  internal/vault/cache_metrics_test.go
  internal/vault/cache_storage_metrics_test.go
  internal/vault/client.go
  internal/vault/credential_provider.go
  internal/vault/credentials/consts.go
  internal/vault/credentials/credential_provider.go
  internal/vault/credentials/helpers.go
  internal/vault/credentials/jwt.go
  internal/vault/credentials/kubernetes.go
  test/integration/infra/main.tf
  test/integration/integration_test.go
  test/integration/vaultauthmethods/terraform/locals.tf
  test/integration/vaultauthmethods/terraform/main.tf
  test/integration/vaultauthmethods/terraform/outputs.tf
  test/integration/vaultauthmethods/terraform/variables.tf
  test/integration/vaultauthmethods_integration_test.go
  test/unit/default-vault-auth-method.bats
Labels: enhancement
