Repository hashicorp/vault-secrets-operator, pull requests merged in 2023-05, with the labels that each got.

#172 VDS: allow for specifying an arbitrary secrets path
  CHANGELOG.md
  Makefile
  api/v1alpha1/vaultdynamicsecret_types.go
  config/crd/bases/secrets.hashicorp.com_vaultdynamicsecrets.yaml
  controllers/vaultdynamicsecret_controller.go
  demo.mk
  demo/infra/app/app.tf
  demo/infra/app/locals.tf
  demo/infra/app/outputs.tf
  demo/infra/app/postgres.tf
  demo/infra/app/variables.tf
  test/integration/vaultdynamicsecret_integration_test.go
Labels: dynamic

#190 VPS: make OtherSANS a string slice
  api/v1alpha1/vaultpkisecret_types.go
  api/v1alpha1/vaultpkisecret_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/crds/secrets.hashicorp.com_vaultpkisecrets.yaml
  config/crd/bases/secrets.hashicorp.com_vaultpkisecrets.yaml
Labels: PKI

#155 Adds approle auth method support
  api/v1alpha1/vaultauth_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/crds/secrets.hashicorp.com_vaultauths.yaml
  chart/templates/default-vault-auth-method.yaml
  chart/values.yaml
  config/crd/bases/secrets.hashicorp.com_vaultauths.yaml
  internal/common/common.go
  internal/vault/cache_storage.go
  internal/vault/credentials/approle.go
  internal/vault/credentials/consts.go
  internal/vault/credentials/credential_provider.go
  internal/vault/credentials/helpers.go
  internal/vault/credentials/jwt.go
  internal/vault/hmac.go
  test/integration/integration_test.go
  test/integration/vaultauthmethods/terraform/main.tf
  test/integration/vaultauthmethods/terraform/outputs.tf
  test/integration/vaultauthmethods/terraform/variables.tf
  test/integration/vaultauthmethods_integration_test.go
  test/unit/default-vault-auth-method.bats
Labels: enhancement

#203 do not delete the vaultAuthMethod before checking for lease revocation status
  test/integration/vaultdynamicsecret_integration_test.go
Labels: CI

#182 Testing Vault Secrets Operator on GKE
  Makefile
  README.md
  demo.mk
  gcp.mk
  test/integration/infra/gke/main.tf
  test/integration/infra/gke/outputs.tf
  test/integration/infra/gke/providers.tf
  test/integration/infra/gke/variables.tf
  test/integration/vaultauthmethods/terraform/main.tf
  test/integration/vaultauthmethods/terraform/variables.tf
  test/integration/vaultauthmethods_integration_test.go
  test/integration/vaultdynamicsecret_integration_test.go
  test/integration/vaultpkisecret_integration_test.go
  test/integration/vaultstaticsecret_integration_test.go
Labels: CI

#212 fix: add ClientCacheKey to the returned of clientCache.Prune() and clientCache unit test
  internal/vault/cache.go
  internal/vault/cache_test.go
Labels: bug

#218 Testing VSO in Azure K8s Service (AKS)
  README.md
  azure.mk
  test/integration/infra/aks/main.tf
  test/integration/infra/aks/outputs.tf
  test/integration/infra/aks/providers.tf
  test/integration/infra/aks/variables.tf
Labels: CI

#219 Updating tests for VSO in EKS
  Makefile
  README.md
  aws.mk
  gcp.mk
  test/integration/infra/eks/main.tf
  test/integration/infra/eks/outputs.tf
  test/integration/infra/eks/providers.tf
  test/integration/infra/eks/variables.tf
Labels: CI
