Repository hashicorp/vault-secrets-operator, pull requests merged in 2023-06, with the labels that each got.

#234 Ensure any previously created k8s Secrets are cleaned up after sync.
  internal/common/common.go
  internal/helpers/secrets.go
  internal/helpers/secrets_test.go
  test/integration/integration_test.go
  test/integration/vaultauthmethods_integration_test.go
  test/integration/vaultdynamicsecret_integration_test.go
  test/integration/vaultpkisecret_integration_test.go
  test/integration/vaultstaticsecret_integration_test.go
Labels: bug

#256 VaultPKISecret: include the CA chain (sans root) in 'tls.crt'
  CHANGELOG.md
  api/v1beta1/vaultpkisecret_types.go
  api/v1beta1/vaultpkisecret_types_test.go
  config/samples/secrets_v1beta1_vaultpkisecret_tls.yaml
  controllers/vaultpkisecret_controller.go
  test/integration/integration_test.go
Labels: enhancement, PKI

#266 Adds controller.imagePullSecrets to helm chart
  CHANGELOG.md
  chart/templates/_helpers.tpl
  chart/templates/deployment.yaml
  chart/values.yaml
  test/unit/deployment.bats
Labels: enhancement

#267 update the kube-rbac-proxy container image from 0.11.0 to latest 0.14.1
  CHANGELOG.md
  chart/values.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: helm

#272 Adding nodeselector and tolerations to Helm chart / Issue #261
  chart/templates/deployment.yaml
  chart/values.yaml
  test/unit/deployment.bats
Labels: enhancement, helm
